### ISSUE TITLE
Can't subset `.data` outside of a data mask context.

### ISSUE THREAD

**Issue by WWz33** [linoferreira/manhattan-vector#1]
Hi! Dr.Lino
When i source "fn-ggmanh_vec.R" and "make-manhattan-vec.R",i got the error.
**"! Can't subset `.data` outside of a data mask context.
Run `rlang::last_trace()` to see where the error occurred."**
Backtrace:
     ▆
  1. ├─base::source("~/.active-rstudio-document")
  2. │ ├─base::withVisible(eval(ei, envir))
  3. │ └─base::eval(ei, envir)
  4. │   └─base::eval(ei, envir)
  5. ├─global ggmanh_vec(...) at ~/.active-rstudio-document:23:0
  6. │ └─... %>% select(.data[[chr]], POScum, .data[[log_pv]]) at ~/.active-rstudio-document:61:2
  7. ├─dplyr::select(., .data[[chr]], POScum, .data[[log_pv]])
  8. ├─dplyr::mutate(., POScum = POS_0 + tot)
  9. ├─dplyr::arrange(., .data[[chr]], POS_0)
 10. ├─dplyr::left_join(df, ., by = .data[[chr]])
 11. ├─dplyr:::left_join.data.frame(df, ., by = .data[[chr]])
 12. │ └─dplyr:::join_mutate(...)
 13. │   └─dplyr:::is_cross_by(by)
 14. │     └─rlang::is_character(x, n = 0L)
 15. ├─<unknown>
 16. └─rlang:::`[[.rlang_fake_data_pronoun`(.data, chr)
 17.   └─rlang:::stop_fake_data_subset(call)
 18.     └─rlang::abort(...)

**Comment by linoferreira** [comment]
Hello and thanks for reporting this bug!

This was caused by an update to the `dplyr` package that changed the syntax of `select()` expressions. I've now updated the code so that it works with more recent versions of the package.

Could you please give it another go with the updated function and let me know if it works for you? Thanks!

**Comment by WWz33** [comment]
Hello,Dr.Lino!
Thanks for your answer.
I regret to tell u that there is still the error on my computer.o(╥﹏╥)o



source("~/.active-rstudio-document**(make-manhattan-vec.R)**")
Show Traceback
Rerun with Debug

Error in { :task 1 failed - "error in evaluating the argument 'x' in selecting a method for function 'slice': Rle of type 'list' is not supported"
8.stop(simpleError(msg, call = expr))
7.e$fun(obj, substitute(ex), parent.frame(), e$data)

6.foreach(o = seq(1, 21, 2)) %dopar% {
P[[o]] <- nrow(df %>% filter(CHR == o))
if (P[[o]] > 10000) {
if ((P[[o]]%%10000) != 0) { ... at .active-rstudio-document#95

5.ggmanh_vec(gwas, chr = "CHR", pos = "BP", log_pv = "LOG10_P",title = "GWAS of standing height in the UK Biobank (EUR population)",ncores = 4) at .active-rstudio-document#24

4.eval(ei, envir)
3.eval(ei, envir)
2.withVisible(eval(ei, envir))
1.source("~/.active-rstudio-document")

**Comment by linoferreira** [comment]
I'm not sure what's going on there... I've made a couple of changes that will fix this if the issue is masking of the `dplyr::slice` function by another package, though I'm not sure that that's the problem.

Could you please try again, ideally on a clean R session and with the example in the `make-manhattan-vec.R` script? (Note that this will download a ~500MB file.)

Thanks!

**Comment by WWz33** [comment]
Hello,Dr.Lino!
When I  ran the  R-scripts on a clean R session，i got two beautiful Manhattan plots(PDF format).
By the way, your R code is useful for beginners like me.
Thanks!

**Comment by linoferreira** [comment]
Great news, glad to hear it! Thanks for the feedback. :)
